export const images: Record<string, any> = {
    arrowBack: require("../../../assets/icons/arrow-back.png"),
    arrowDown: require("../../../assets/icons/arrow-down.png"),
    arrowRight: require("../../../assets/icons/arrow-right.png"),
    heart: require("../../../assets/images/heart.png"),
    kidney: require("../../../assets/images/kidney.png"),
    liver: require("../../../assets/images/liver.png"),
    lungs: require("../../../assets/images/lungs.png"),
    dental: require("../../../assets/images/teeth.png"),
    ambulance: require("../../../assets/icons/ambulance.png"),
    opd: require("../../../assets/icons/opd.png"),
    texture: require("../../../assets/images/texture.png"),
    kidneyIcon: require("../../../assets/images/kidney.png"),
    liverIcon: require("../../../assets/images/liver.png"),
};

const FEMALE_DOCTOR_IMAGE =
    "https://fra.cloud.appwrite.io/v1/storage/buckets/691c5f6e001de2ba402c/files/6a663aea0029ec8d2491/view?project=687534a40002a65f2150";
const MALE_DOCTOR_IMAGE =
    "https://fra.cloud.appwrite.io/v1/storage/buckets/691c5f6e001de2ba402c/files/6a663ad80037b48b814c/view?project=687534a40002a65f2150";

/** Fallback list — home prefers live Appwrite doctors via useDoctorStore */
export const topDoctorList = [
    {
        name: "Dr. (Lt. Col.) Nasima Rahman",
        name_bn: "ডাঃ (লেঃ কর্ণেল) নাছিমা রহমান",
        specialty: "Gynecology & Obstetrics",
        specialty_bn: "স্ত্রীরোগ ও প্রসূতি",
        hourlyRate: 0,
        image: FEMALE_DOCTOR_IMAGE,
        experience:
            "FCPS (Gynae & Obs), CCD (Diabetology), MBBS. Trained in Female Pelvic Medicine and Reconstructive Surgery. Associate Professor & Classified Specialist (Gynae & Obs) at Combined Military Hospital (CMH), Ramu, Cox's Bazar. Consultant (Gynecology & Obstetrics).",
        experience_bn:
            "এফসিপিএস (গাইনী ও অবস), সিসিডি (ডায়াবেটোলজি), এমবিবিএস। ফিমেল পেলভিক মেডিসিন ও রিকনস্ট্রাক্টিভ সার্জারিতে প্রশিক্ষণপ্রাপ্ত। সহযোগী অধ্যাপক ও ক্লাসিফাইড স্পেশালিস্ট (গাইনী ও অবস), কম্বাইন্ড মিলিটারী হাসপাতাল (সিএমএইচ), রামু, কক্সবাজার। কনসালটেন্ট (স্ত্রীরোগ ও প্রসূতি বিভাগ).",
        specialties: [
            "Prenatal checkup",
            "Treatment for miscarriage risk and complicated miscarriage",
            "Gestational diabetes treatment",
            "Treatment for irregular menstruation",
            "Treatment for scanty and excessive menstrual bleeding",
            "Treatment for leucorrhoea (white discharge)",
            "Treatment for uterine cysts and tumors",
            "Normal delivery",
            "Cesarean (C-section) surgery",
            "Uterine prolapse surgery",
            "Infertility treatment",
            "Adolescent healthcare",
            "Menopause and post-menopausal healthcare",
        ],
        specialties_bn: [
            "গর্ভকালীন চেকআপ",
            "গর্ভপাতের ঝুঁকির চিকিৎসা ও জটিল গর্ভপাতের চিকিৎসা",
            "গর্ভকালীন ডায়াবেটিস চিকিৎসা",
            "অনিয়মিত মাসিক এর চিকিৎসা",
            "স্বল্প ও অতিরিক্ত রক্ত স্রাবের চিকিৎসা",
            "সাদা স্রাবের চিকিৎসা",
            "জরায়ুর সিস্ট ও টিউমার এর চিকিৎসা",
            "নরমাল ডেলিভারি",
            "সিজার (সি-সেকশন) অপারেশন",
            "জরায়ু প্রলেপস অপারেশন",
            "বন্ধ্যাত্ব (বাচ্চা না হওয়া) চিকিৎসা",
            "কিশোরী স্বাস্থ্যসেবা",
            "মেনোপজ (মাসিক বন্ধ হওয়া) ও পরবর্তী স্বাস্থ্যসেবা",
        ],
        $id: "6a65e4c700124f8c8151",
    },
    {
        name: "Dr. Nrinmoy Biswas",
        name_bn: "ডাঃ নৃন্ময় বিশ্বাস",
        specialty: "Gynecology & Obstetrics",
        specialty_bn: "স্ত্রীরোগ ও প্রসূতি",
        hourlyRate: 0,
        image: MALE_DOCTOR_IMAGE,
        experience:
            "MBBS, DGO, FMAS (India). Fellowship in Gynae & Obs (India). FIGO Trained Fistula Surgeon (Ethiopia & Kenya). Advanced training in infertility treatment (India). Senior Consultant (Gynecology & Obstetrics).",
        experience_bn:
            "এমবিবিএস, ডিজিও, এফএমআইএস (ভারত)। ফেলোশিপ ইন গাইনী ও অবস (ভারত)। ফিগো ট্রেইন্ড ফিস্টুলা সার্জন (ইথিওপিয়া ও কেনিয়া)। বন্ধ্যাত্ব চিকিৎসায় উচ্চতর প্রশিক্ষণপ্রাপ্ত (ভারত)। সিনিয়র কনসালটেন্ট (স্ত্রীরোগ ও প্রসূতি বিভাগ).",
        specialties: [
            "Prenatal checkup",
            "Treatment for miscarriage risk and complicated miscarriage",
            "Gestational diabetes treatment",
            "Treatment for irregular menstruation",
            "Treatment for scanty and excessive menstrual bleeding",
            "Treatment for leucorrhoea (white discharge)",
            "Treatment for uterine cysts and tumors",
            "Normal delivery",
            "Cesarean (C-section) surgery",
            "Fistula surgery due to delivery complications",
            "Uterine prolapse surgery",
            "Infertility treatment",
            "Adolescent healthcare",
            "Menopause and post-menopausal healthcare",
            "Family planning consultation",
        ],
        specialties_bn: [
            "গর্ভকালীন চেকআপ",
            "গর্ভপাতের ঝুঁকির চিকিৎসা ও জটিল গর্ভপাতের চিকিৎসা",
            "গর্ভকালীন ডায়াবেটিস চিকিৎসা",
            "অনিয়মিত মাসিক এর চিকিৎসা",
            "স্বল্প ও অতিরিক্ত রক্ত স্রাবের চিকিৎসা",
            "সাদা স্রাবের চিকিৎসা",
            "জরায়ুর সিস্ট ও টিউমার এর চিকিৎসা",
            "নরমাল ডেলিভারি",
            "সিজার (সি-সেকশন) অপারেশন",
            "প্রসব জটিলতা জনিত ফিস্টুলা অপারেশন",
            "জরায়ু প্রলেপস অপারেশন",
            "বন্ধ্যাত্ব (বাচ্চা না হওয়া) চিকিৎসা",
            "কিশোরী স্বাস্থ্যসেবা",
            "মেনোপজ (মাসিক বন্ধ হওয়া) ও পরবর্তী স্বাস্থ্যসেবা",
            "পরিবার পরিকল্পনা পরামর্শ",
        ],
        $id: "6a65e4c9002aa3a7f188",
    },
    {
        name: "Dr. Abdul Mannan",
        name_bn: "ডাঃ আব্দুল মান্নান",
        specialty: "Pediatrics",
        specialty_bn: "শিশুরোগ",
        hourlyRate: 0,
        image: MALE_DOCTOR_IMAGE,
        experience:
            "MBBS; DCH (Child Health). Specialist in newborn and child diseases with 25 years of clinical experience. BMDC Reg. No. A25729. Consultant, Pediatrics Department.",
        experience_bn:
            "এমবিবিএস; ডিসিএইচ (শিশু স্বাস্থ্য)। নবজাতক ও শিশু রোগ বিশেষজ্ঞ — ২৫ বছরের ক্লিনিক্যাল অভিজ্ঞতা সম্পন্ন। বিএমডিসি রেজিঃ এ২৫৭২৯। কনসালটেন্ট শিশুরোগ বিভাগ.",
        specialties: [
            "Fever, cough, cold, or pneumonia",
            "Fever with seizures",
            "Abdominal pain and stomach-related problems",
            "Jaundice or liver problems",
            "Shortness of breath, asthma, or fainting",
            "Delayed development or hormone-related issues",
            "Tonsil problems in children",
            "Anemia",
            "Swelling of eyes/face or change in urine color",
            "Diarrhea or loose motions",
            "Pain or swelling in legs and joints",
            "Frequent urination or bedwetting",
            "Newborn care and newborn screening",
            "Newborn jaundice, blood infections, or umbilical cord infections",
            "Low birth weight, seizures, or loss of appetite",
            "Vomiting, weight loss, or malnutrition",
        ],
        specialties_bn: [
            "জ্বর, কাশি, সর্দি বা নিউমোনিয়া",
            "জ্বরের সাথে খিঁচুনি/মৃগীরোগ",
            "পেটব্যথা বা পেট সংক্রান্ত যেকোনো সমস্যা",
            "জন্ডিস বা লিভারের সমস্যা",
            "শ্বাসকষ্ট, হাঁপানি বা অজ্ঞান হয়ে যাওয়া",
            "বিকাশের সমস্যা বা হরমোনজনিত সমস্যা",
            "শিশুদের টনসিলের সমস্যা",
            "রক্তশূন্যতা (অ্যানিমিয়া)",
            "চোখ/মুখ ফুলে যাওয়া বা প্রস্রাবের রঙ পরিবর্তন",
            "ডায়রিয়া বা পাতলা পায়খানা",
            "পা ও জয়েন্টে ব্যথা বা ফোলা",
            "ঘন ঘন প্রস্রাব বা বিছানায় প্রস্রাব",
            "নবজাতকের যেকোনো চিকিৎসা ও নিউবর্ন স্ক্রিনিং",
            "নবজাতকের জন্ডিস, রক্তের সংক্রমণ বা নাভির সংক্রমণ",
            "কম ওজন, খিঁচুনি বা খাবারে অনীহা",
            "বমি, ওজন কমে যাওয়া বা অপুষ্টি",
        ],
        $id: "6a65e4cc002b1d1a52c1",
    },
    {
        name: "Dr. Farhana Faruq",
        name_bn: "ডাঃ ফারহানা ফারুক",
        specialty: "Gynecology & Obstetrics",
        specialty_bn: "স্ত্রীরোগ ও প্রসূতি",
        hourlyRate: 0,
        image: FEMALE_DOCTOR_IMAGE,
        experience:
            "MBBS, MPH, DMU, CCD, PGT (Gynae & Obs). FIGO Trained Fistula Surgeon (Ethiopia). Residential Surgeon, Department of Gynecology and Obstetrics.",
        experience_bn:
            "এমবিবিএস, এমপিএইচ, ডিএমইউ, সিসিডি, পিজিটি (গাইনী ও অবস)। ফিগো ট্রেইন্ড ফিস্টুলা সার্জন (ইথিওপিয়া)। রেসিডেন্সিয়াল সার্জন (স্ত্রীরোগ ও প্রসূতি বিভাগ).",
        specialties: [
            "Prenatal checkup",
            "Treatment for miscarriage risk and complicated miscarriage",
            "Gestational diabetes treatment",
            "Treatment for irregular menstruation",
            "Treatment for scanty and excessive menstrual bleeding",
            "Treatment for leucorrhoea (white discharge)",
            "Treatment for uterine cysts and tumors",
            "Normal delivery",
            "Cesarean (C-section) surgery",
            "Fistula surgery due to delivery complications",
            "Uterine prolapse surgery",
            "Infertility treatment",
            "Adolescent healthcare",
            "Menopause and post-menopausal healthcare",
            "Family planning consultation",
        ],
        specialties_bn: [
            "গর্ভকালীন চেকআপ",
            "গর্ভপাতের ঝুঁকির চিকিৎসা ও জটিল গর্ভপাতের চিকিৎসা",
            "গর্ভকালীন ডায়াবেটিস চিকিৎসা",
            "অনিয়মিত মাসিক এর চিকিৎসা",
            "স্বল্প ও অতিরিক্ত রক্ত স্রাবের চিকিৎসা",
            "সাদা স্রাবের চিকিৎসা",
            "জরায়ুর সিস্ট ও টিউমার এর চিকিৎসা",
            "নরমাল ডেলিভারি",
            "সিজার (সি-সেকশন) অপারেশন",
            "প্রসব জটিলতা জনিত ফিস্টুলা অপারেশন",
            "জরায়ু প্রলেপস অপারেশন",
            "বন্ধ্যাত্ব (বাচ্চা না হওয়া) চিকিৎসা",
            "কিশোরী স্বাস্থ্যসেবা",
            "মেনোপজ (মাসিক বন্ধ হওয়া) ও পরবর্তী স্বাস্থ্যসেবা",
            "পরিবার পরিকল্পনা পরামর্শ",
        ],
        $id: "6a65e4ce001d7f1b8bac",
    },
    {
        name: "Dr. A K M Arif Uddin Ahmed",
        name_bn: "ডাঃ এ কে এম আরিফ উদ্দিন আহমেদ",
        specialty: "Medicine & Diabetes",
        specialty_bn: "মেডিসিন ও ডায়াবেটিস",
        hourlyRate: 0,
        image: MALE_DOCTOR_IMAGE,
        experience:
            "MBBS, CCD, MPH, PGT (Medicine and Cardiology). Former Assistant Professor (Clinical Medicine). Chief Medical Officer and Consultant (Medicine & Diabetes Department).",
        experience_bn:
            "এমবিবিএস, সিসিডি, এমপিএইচ, পিজিটি (মেডিসিন ও হৃদরোগ)। প্রাক্তন সহকারী অধ্যাপক (ক্লিনিক্যাল মেডিসিন)। চীফ মেডিকেল অফিসার ও কনসালটেন্ট (মেডিসিন ও ডায়াবেটিস বিভাগ).",
        specialties: [
            "General medicine consultation",
            "Diabetes management",
            "Cardiology-related medical care (PGT training)",
            "Clinical medicine",
        ],
        specialties_bn: [
            "সাধারণ মেডিসিন পরামর্শ",
            "ডায়াবেটিস ব্যবস্থাপনা",
            "হৃদরোগ সংশ্লিষ্ট মেডিকেল কেয়ার (পিজিটি প্রশিক্ষণ)",
            "ক্লিনিক্যাল মেডিসিন",
        ],
        $id: "6a65e4cf0039d8958b08",
    },
];
